### ISSUE TITLE
Support for Sentry Client 2.0

### ISSUE THREAD

**Issue by sebastianwahn** [transcovo/bunyan-sentry-stream#15]
Sentry is deprecating its explicit node library raven, instead they will switch to a mono repository for javascript. It is available at https://github.com/getsentry/sentry-javascript
The package hast currently a beta status, so the old raven client is still maintained.

The Client can be installed with `npm install @sentry/node`. Using the new library with bunyan-sentry-stream fails though.

Stack trace (I replaced the full path with a relative one):

```
(node:55731) UnhandledPromiseRejectionWarning: TypeError: scope.applyToEvent is not a function
    at NodeClient.<anonymous> (./node_modules/@sentry/core/src/base.ts:238:20)
    at step (./node_modules/@sentry/core/dist/base.js:40:23)
    at Object.next (./node_modules/@sentry/core/dist/base.js:21:53)
    at ./node_modules/@sentry/core/dist/base.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (./node_modules/@sentry/core/dist/base.js:11:12)
    at NodeClient.BaseClient.prepareEvent (./node_modules/@sentry/core/dist/base.js:240:16)
    at NodeClient.<anonymous> (./node_modules/@sentry/core/src/base.ts:272:33)
    at step (./node_modules/@sentry/core/dist/base.js:40:23)
    at Object.next (./node_modules/@sentry/core/dist/base.js:21:53)
    at ./node_modules/@sentry/core/dist/base.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (./node_modules/@sentry/core/dist/base.js:11:12)
    at NodeClient.BaseClient.processEvent (./node_modules/@sentry/core/dist/base.js:290:16)
    at NodeClient.<anonymous> (./node_modules/@sentry/core/src/base.ts:136:17)
    at step (./node_modules/@sentry/core/dist/base.js:40:23)
    at Object.next (./node_modules/@sentry/core/dist/base.js:21:53)
    at ./node_modules/@sentry/core/dist/base.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (./node_modules/@sentry/core/dist/base.js:11:12)
    at NodeClient.BaseClient.captureEvent (./node_modules/@sentry/core/dist/base.js:165:16)
    at NodeClient.<anonymous> (./node_modules/@sentry/core/src/base.ts:129:16)
    at step (./node_modules/@sentry/core/dist/base.js:40:23)
    at Object.next (./node_modules/@sentry/core/dist/base.js:21:53)
    at fulfilled (./node_modules/@sentry/core/dist/base.js:12:58)
    at <anonymous>
```

**Comment by zishon89us** [comment]
Is it possible now? @sentry/node integration to wrap bunyan log calls as breadcrumbs

SO link: https://stackoverflow.com/questions/53310580/sentry-node-integration-to-wrap-bunyan-log-calls-as-breadcrumbs
